### ISSUE TITLE
App Title & Icon Not Displayed In Top Left Corner, Inconsistent with Material Design

### ISSUE THREAD

**Issue by bmccoy11** [demantz/RFAnalyzer#19]
Hello again,

The app title and icon isn't displayed in the top left corner, which is inconsistent with other Material apps and the app would look nicer with it.

**Comment by demantz** [comment]
Thx for this bug report too ;) I also fixed it in the alpha (1.13alpha3): https://github.com/demantz/RFAnalyzer/blob/scan_feature/RFAnalyzer.apk?raw=true

Could you confirm that this version acts as you would expect it?

Cheers,
Dennis

**Comment by bmccoy11** [comment]
The icon is still missing in the top left corner.

**Comment by demantz** [comment]
I think this is the default behavior for material design. Non of the system apps is showing an icon...

**Comment by bmccoy11** [comment]
Oh, you're right - the icon shouldn't be in the top left corner, but the overflow menu should be (and it should be a hamburger button too)

**Comment by demantz** [comment]
You're right. But the sidebar/drawer should contain the app's main menu (like settings and help).. All the other actions (like autoscale) remain in the overflow on the right. I will fix this after all the more important features are implemented. Thanks for the hint ;)
