### ISSUE TITLE
Support for rad1o

### ISSUE THREAD

**Issue by seelmann** [demantz/RFAnalyzer#26]
Support for the [rad1o badge](http://rad1o.de/) is added by this [pull request}(https://github.com/demantz/hackrf_android/pull/5). In the meantime a (temporary) forked app can be found at https://github.com/rad1o/RFAnalyzer.

**Comment by demantz** [comment]
I'm sorry that this took me more than a year to complete! I did not work on the app for a long time.. Today I published a beta of RF Analyzer version 1.13 which includes the latest hackrf_analyzer version. It's available for beta testers on the Play Store (https://play.google.com/apps/testing/com.mantz_it.rfanalyzer) or on the git branch release_ver13.

The beta should now work fine with the rad1o (the new USB product ID is now also recognized correctly) but I don't have a rad1o for testing. I'm closing the issue.. however, if there are still problems with the rad1o please open a new issue! Thank you and again: sorry for the long delay..
