### ISSUE TITLE
Worked in Moto X  1ra Gen.

### ISSUE THREAD

**Issue by sabas1080** [demantz/RFAnalyzer#27]
Hi

I have worked in Moto X 1ra Gen. with sdr-rtl

http://imgur.com/nUZ0CRE

There a paypal account where to donate ?

Thanks for you work

**Comment by demantz** [comment]
Nice! I've added the Moto X to the list: https://github.com/demantz/hackrf_android#tested-devices

You can find donate buttons for paypal, bitcoin and flattr on my blog: http://tech.mantz-it.com/

Thanks,
Dennis
